const CHANNELS = [
  { name: "MBC1", url: "https://shd-gcp-live-orng.shahid.net/live/bitmovin-mbc-1-na/eec141533c90dd34722c503a296dd0d8/index.m3u8", type: "hls" },
  { name: "قناة 2", url: "http://185.191.126.127:8080/live//b0:99:d7:15:88:50/3090914536649669/325793.ts", type: "ts" },
  { name: "قناة 3", url: "http://lynovo.cc/live/407F2F55785345F/xiAYSAZIpR/1339224.ts", type: "ts" },
  { name: "قناة 4", url: "http://obsfullhd.tv:25461/live/lacherejc/OannyVVIL2/140.ts", type: "ts" },
  { name: "قناة 5",  url: "", type: "hls" },
  { name: "قناة 6",  url: "", type: "hls" },
  { name: "قناة 7",  url: "", type: "hls" },
  { name: "قناة 8",  url: "", type: "hls" },
  { name: "قناة 9",  url: "", type: "hls" },
  { name: "قناة 10", url: "", type: "hls" },
  { name: "قناة 11", url: "", type: "hls" },
  { name: "قناة 12", url: "", type: "hls" },
  { name: "قناة 13", url: "", type: "hls" },
  { name: "قناة 14", url: "", type: "hls" },
  { name: "قناة 15", url: "", type: "hls" },
  { name: "قناة 16", url: "", type: "hls" },
  { name: "قناة 17", url: "", type: "hls" },
  { name: "قناة 18", url: "", type: "hls" },
  { name: "قناة 19", url: "", type: "hls" },
  { name: "قناة 20", url: "", type: "hls" },
  { name: "قناة 21", url: "", type: "hls" },
  { name: "قناة 22", url: "", type: "hls" },
  { name: "قناة 23", url: "", type: "hls" },
  { name: "قناة 24", url: "", type: "hls" },
  { name: "قناة 25", url: "", type: "hls" },
  { name: "قناة 26", url: "", type: "hls" },
  { name: "قناة 27", url: "", type: "hls" },
  { name: "قناة 28", url: "", type: "hls" },
  { name: "قناة 29", url: "", type: "hls" },
  { name: "قناة 30", url: "", type: "hls" }
];
